In [ ]:
from google.colab import drive
drive.mount('/content/GoogleDrive')

Drive already mounted at /content/GoogleDrive; to attempt to forcibly remount, call drive.mount("/content/GoogleDrive", force_remount=True).

In [ ]:
import pandas as pd
data_original = pd.read_csv(r"/content/GoogleDrive/MyDrive/Colab Notebooks/Tracks/Chevron/Train/training.csv")

print(f'the shape of the dataset is {data_original.shape}')
print(f'the type of the dataset is \n{data_original.dtypes}')

the shape of the dataset is (29692, 31)
the type of the dataset is
Unnamed: 0                        int64
surface_x                       float64
surface_y                       float64
bh_x                            float64
bh_y                            float64
standardized_operator_name        int64
gross_perforated_length         float64
number_of_stages                float64
total_proppant                  float64
total_fluid                     float64
true_vertical_depth             float64
ffs_frac_type                    object
proppant_intensity              float64
frac_fluid_intensity            float64
average_stage_length            float64
average_proppant_per_stage      float64
average_frac_fluid_per_stage    float64
proppant_to_frac_fluid_ratio    float64
frac_fluid_to_proppant_ratio    float64
bin_lateral_length              float64
pad_id                            int64
relative_well_position           object
batch_frac_classification        object
well_family_relationship         object
frac_type                        object
frac_seasoning                  float64
horizontal_midpoint_x           float64
horizontal_midpoint_y           float64
horizontal_toe_x                float64
horizontal_toe_y                float64
OilPeakRate                     float64
dtype: object

In [ ]:
data_original.head()

,Unnamed: 0,surface_x,surface_y,bh_x,bh_y,standardized_operator_name,gross_perforated_length,number_of_stages,total_proppant,total_fluid,true_vertical_depth,ffs_frac_type,proppant_intensity,frac_fluid_intensity,average_stage_length,average_proppant_per_stage,average_frac_fluid_per_stage,proppant_to_frac_fluid_ratio,frac_fluid_to_proppant_ratio,bin_lateral_length,pad_id,relative_well_position,batch_frac_classification,well_family_relationship,frac_type,frac_seasoning,horizontal_midpoint_x,horizontal_midpoint_y,horizontal_toe_x,horizontal_toe_y,OilPeakRate
0,0,1383493.751,717329.2368,1382854.564,712767.3700,1121,3963.582677,NaN,76000.0000,NaN,8712.598425,NaN,19.174572,NaN,NaN,NaN,NaN,NaN,NaN,1.0,102604,Standalone Well,Unknown,Standalone Well,Primary Frac,NaN,1383030.678,714796.3610,1382668.912,712798.4321,46.623023
1,1,1380344.035,711916.2732,1379738.429,707860.5643,1022,3179.133858,NaN,113000.0000,5.610964e+05,8627.952756,NaN,35.544272,176.493480,NaN,NaN,NaN,0.201391,4.965455,1.0,108497,Outer Well,Unknown,Infill Child Well,Primary Frac,NaN,1379965.126,709541.7145,1379630.025,707907.6708,59.750009
2,2,1379915.895,717845.0063,1379274.644,713471.9952,1304,3810.039370,12.0,286571.4286,1.621424e+06,8801.181102,NaN,75.214821,425.566078,317.503281,23880.952380,135118.62610,0.176741,5.658008,1.0,108526,Standalone Well,Non-Batch Frac,Standalone Well,Primary Frac,92.0,1379357.250,715381.2327,1378960.372,713530.4490,10.785716
3,3,1383567.443,706640.2010,1382891.477,702068.3838,1022,3723.425197,11.0,106878.9286,4.377134e+05,8635.826772,NaN,28.704465,117.556659,338.493200,9716.266234,39792.12953,0.244176,4.095414,1.0,105631,Standalone Well,Unknown,Standalone Well,Primary Frac,NaN,1383099.610,704058.8508,1382727.299,702098.4882,123.797638
4,4,1378962.585,702623.9787,1379643.546,707204.9131,1022,3811.023622,NaN,112789.7143,6.229802e+05,8664.370079,NaN,29.595648,163.467933,NaN,NaN,NaN,0.181049,5.523377,1.0,103717,Outer Well,Unknown,Infill Child Well,Primary Frac,NaN,1379546.414,705150.7519,1379987.487,707123.7258,102.309540

In [ ]:
data_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29692 entries, 0 to 29691
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    29692 non-null  int64
 1   surface_x                     29692 non-null  float64
 2   surface_y                     29692 non-null  float64
 3   bh_x                          27605 non-null  float64
 4   bh_y                          27605 non-null  float64
 5   standardized_operator_name    29692 non-null  int64
 6   gross_perforated_length       22135 non-null  float64
 7   number_of_stages              2752 non-null   float64
 8   total_proppant                19080 non-null  float64
 9   total_fluid                   19076 non-null  float64
 10  true_vertical_depth           28197 non-null  float64
 11  ffs_frac_type                 14585 non-null  object
 12  proppant_intensity            18971 non-null  float64
 13  frac_fluid_intensity          18946 non-null  float64
 14  average_stage_length          2724 non-null   float64
 15  average_proppant_per_stage    2689 non-null   float64
 16  average_frac_fluid_per_stage  2687 non-null   float64
 17  proppant_to_frac_fluid_ratio  18656 non-null  float64
 18  frac_fluid_to_proppant_ratio  18656 non-null  float64
 19  bin_lateral_length            22135 non-null  float64
 20  pad_id                        29692 non-null  int64
 21  relative_well_position        20467 non-null  object
 22  batch_frac_classification     20467 non-null  object
 23  well_family_relationship      20467 non-null  object
 24  frac_type                     29692 non-null  object
 25  frac_seasoning                14768 non-null  float64
 26  horizontal_midpoint_x         28691 non-null  float64
 27  horizontal_midpoint_y         28691 non-null  float64
 28  horizontal_toe_x              28981 non-null  float64
 29  horizontal_toe_y              28981 non-null  float64
 30  OilPeakRate                   19306 non-null  float64
dtypes: float64(23), int64(3), object(5)
memory usage: 7.0+ MB

In [ ]:
data_original.columns

Index(['Unnamed: 0', 'surface_x', 'surface_y', 'bh_x', 'bh_y',
       'standardized_operator_name', 'gross_perforated_length',
       'number_of_stages', 'total_proppant', 'total_fluid',
       'true_vertical_depth', 'ffs_frac_type', 'proppant_intensity',
       'frac_fluid_intensity', 'average_stage_length',
       'average_proppant_per_stage', 'average_frac_fluid_per_stage',
       'proppant_to_frac_fluid_ratio', 'frac_fluid_to_proppant_ratio',
       'bin_lateral_length', 'pad_id', 'relative_well_position',
       'batch_frac_classification', 'well_family_relationship', 'frac_type',
       'frac_seasoning', 'horizontal_midpoint_x', 'horizontal_midpoint_y',
       'horizontal_toe_x', 'horizontal_toe_y', 'OilPeakRate'],
      dtype='object')

In [ ]:
data_original.drop(["Unnamed: 0", "frac_type", "standardized_operator_name", "pad_id"], axis=1, inplace=True)

In [ ]:
data_original.dropna(subset=["OilPeakRate"], inplace=True)

In [ ]:
data_original.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19306 entries, 0 to 29436
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   surface_x                     19306 non-null  float64
 1   surface_y                     19306 non-null  float64
 2   bh_x                          17882 non-null  float64
 3   bh_y                          17882 non-null  float64
 4   gross_perforated_length       19148 non-null  float64
 5   number_of_stages              2643 non-null   float64
 6   total_proppant                17912 non-null  float64
 7   total_fluid                   17866 non-null  float64
 8   true_vertical_depth           19201 non-null  float64
 9   ffs_frac_type                 14310 non-null  object
 10  proppant_intensity            17872 non-null  float64
 11  frac_fluid_intensity          17821 non-null  float64
 12  average_stage_length          2620 non-null   float64
 13  average_proppant_per_stage    2595 non-null   float64
 14  average_frac_fluid_per_stage  2582 non-null   float64
 15  proppant_to_frac_fluid_ratio  17501 non-null  float64
 16  frac_fluid_to_proppant_ratio  17501 non-null  float64
 17  bin_lateral_length            19148 non-null  float64
 18  relative_well_position        19306 non-null  object
 19  batch_frac_classification     19306 non-null  object
 20  well_family_relationship      19306 non-null  object
 21  frac_seasoning                14479 non-null  float64
 22  horizontal_midpoint_x         19249 non-null  float64
 23  horizontal_midpoint_y         19249 non-null  float64
 24  horizontal_toe_x              19249 non-null  float64
 25  horizontal_toe_y              19249 non-null  float64
 26  OilPeakRate                   19306 non-null  float64
dtypes: float64(23), object(4)
memory usage: 4.1+ MB

In [ ]:
from sklearn.preprocessing import OneHotEncoder
categorical_cols = ['ffs_frac_type', 'relative_well_position', 'batch_frac_classification', 'well_family_relationship']
data_cat = data_original[categorical_cols]
cat_encoder = OneHotEncoder()
data_category_val = cat_encoder.fit_transform(data_cat).toarray()
data_hot_encoded = pd.DataFrame(data_category_val, index=data_original.index)
data_other_cols = data_original.drop(columns=categorical_cols)
data_out = pd.concat([data_hot_encoded, data_other_cols], axis=1)

In [ ]:
from sklearn.impute import KNNImputer
import numpy as np

data_out.columns = data_out.columns.astype(str)
data_out = data_out.replace([np.inf, -np.inf], np.nan)
imputer = KNNImputer(n_neighbors= 5)
data1 = imputer.fit_transform(data_out)

In [ ]:
data2 = pd.DataFrame(data1, columns=imputer.get_feature_names_out())

In [ ]:
data2.to_csv('/content/GoogleDrive/MyDrive/data/data3.csv')